---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argoproj-metrics-poc-apiserver
  namespace: default
  labels:
    api: argoproj-metrics-poc
    apiserver: "true"
spec:
  selector:
    matchLabels:
      api: argoproj-metrics-poc
      apiserver: "true"
  replicas: 1
  template:
    metadata:
      labels:
        api: argoproj-metrics-poc
        apiserver: "true"
    spec:
      containers:
      - name: apiserver
        image: argoproj-metrics-poc
        volumeMounts:
        - name: apiserver-certs
          mountPath: /apiserver.local.config/certificates
          readOnly: true
        command:
        - "./apiserver"
        args:
        - "--etcd-servers=http://etcd-svc:2379"
        - "--tls-cert-file=/apiserver.local.config/certificates/tls.crt"
        - "--tls-private-key-file=/apiserver.local.config/certificates/tls.key"
        - "--audit-log-path=-"
        - "--feature-gates=APIPriorityAndFairness=false"
        - "--audit-log-maxage=0"
        - "--audit-log-maxbackup=0"
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
      volumes:
      - name: apiserver-certs
        secret:
          secretName: argoproj-metrics-poc
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: argoproj-metrics-poc
  namespace: default
  labels:
    api: argoproj-metrics-poc
    apiserver: "true"
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURzekNDQXB1Z0F3SUJBZ0lJYk1WMyt0RzZiRGt3RFFZSktvWklodmNOQVFFTEJRQXdkREVMTUFrR0ExVUUKQmhNQ2RXNHhDekFKQmdOVkJBZ01Bbk4wTVFvd0NBWURWUVFIREFGc01Rb3dDQVlEVlFRS0RBRnZNUXN3Q1FZRApWUVFMREFKdmRURXpNREVHQTFVRUF3d3FZWEpuYjNCeWIyb3RiV1YwY21samN5MXdiMk10WTJWeWRHbG1hV05oCmRHVXRZWFYwYUc5eWFYUjVNQjRYRFRJeU1URXhOVEl4TWpVME5sb1hEVE15TVRFeE1qSXhNalUwTmxvd0t6RXAKTUNjR0ExVUVBeE1nWVhKbmIzQnliMm90YldWMGNtbGpjeTF3YjJNdVpHVm1ZWFZzZEM1emRtTXdnZ0VpTUEwRwpDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRFpFS281R0hQZWFBYm1Bb2NrMm84ZmZ5ZnkxY3FWCkRqNVA2d3JjU0ZIODFpSHJ2aU8rUHFIWmw4SVd4eDkwSCt4L3JPeWt4dU53dG5tV3gxdHVPWnlvdVZFVTQ3RXUKRVBoT0h4R0FqbmxVOXgxVit2QnhKRHYwcDJyT040KzlqZkg0UjZLbjg0Y2haOE9NVlNzUzJNZjJVN0dYcVdlZwpFcjBKSkc1SFdSRHZoUDBWU2JQVTJob2gwb3lvNUp5TjhTKzhZUFJ0RUtYb0VkZlVYVGpIZU1aSEtmYUs3K2xnCm9USm9uUDFGejF6czN0QmNSazNiVmtlb1dmQTBaS0c1K3FORXEyLzR0RXhBcWhJcVlXZUtjY2t3OEMvbkl3T3MKYmVqQjBySlN5Zis1cjdpdjlEbzlVckZvTmMvTmZnalRZdld4bUJQcmN1d3VibHFxcStyU3hVVUpBZ01CQUFHagpnWkV3Z1k0d0RnWURWUjBQQVFIL0JBUURBZ1dnTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFmQmdOVkhTTUVHREFXZ0JUYkxoemgvV3plSHBmZ1VIU3dZWmtQYTdYNUpEQThCZ05WSFJFRU5UQXoKZ2dsc2IyTmhiR2h2YzNTQ0lHRnlaMjl3Y205cUxXMWxkSEpwWTNNdGNHOWpMbVJsWm1GMWJIUXVjM1pqaHdSLwpBQUFCTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBT3pCMWlUTm1Eb2xLMGNzVG5ONEV5QWk3WGxLVnI0cDlHCko4Y2lsdGpMQ09KTURpYnBHQ2xPZmxLRnYwLzA1SWpUUUpvM1pJTG9yTTk5K1Z1WjdlT1JqdW5CUzN2QXZLNkoKNFJMNDlZbjJYdi8vOFdXeXhhajJDV0dxcDNtU0l6aDhkSmlJNTZMaE1pS0dLeGd6VlowRGRCd1Bqa0ZXSEo1NApoSFRTQVl3ZmxueEVxQURTNU1iVXVkanVxdE1KVHhKZTZRWGVvcFdpZUdBaHY3NDBGdVcxeVJ0U3YrLzVvSllXCisrTklmWG1PanJmMVBkSms4UlVSWFJZMkNOTllya05UcW51SE82TnlzNWFBUFNOQWJaYk4wbGp2ZmE0THcwV1IKbHo2MHorRlhHeGcvNVNkQ2ZwTWpvdEIxR1JsMFltQlNlM2x1TXhYaTJ3TzJ0dlprUlI1RgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBMlJDcU9SaHozbWdHNWdLSEpOcVBIMzhuOHRYS2xRNCtUK3NLM0VoUi9OWWg2NzRqCnZqNmgyWmZDRnNjZmRCL3NmNnpzcE1iamNMWjVsc2RiYmptY3FMbFJGT094TGhENFRoOFJnSTU1VlBjZFZmcncKY1NRNzlLZHF6amVQdlkzeCtFZWlwL09ISVdmRGpGVXJFdGpIOWxPeGw2bG5vQks5Q1NSdVIxa1E3NFQ5RlVtegoxTm9hSWRLTXFPU2NqZkV2dkdEMGJSQ2w2QkhYMUYwNHgzakdSeW4yaXUvcFlLRXlhSno5UmM5YzdON1FYRVpOCjIxWkhxRm53TkdTaHVmcWpSS3R2K0xSTVFLb1NLbUZuaW5ISk1QQXY1eU1Eckczb3dkS3lVc24vdWErNHIvUTYKUFZLeGFEWFB6WDRJMDJMMXNaZ1Q2M0xzTG01YXFxdnEwc1ZGQ1FJREFRQUJBb0lCQUVIV2dpc0xOYW5SMTdYUQpNbm1GS1VBZWExbUdhd25HNWpPTFVTSDdkWkxBeUUwZXdPeWxScVlmRjZtYy8vZFM3NExTU255NExxZ3pVTEhoCkNlUm02Uk5zRWlISjVpWFkwOWV1S0xyYmZBVy9abEI3Nm80R3RZREJmdTNKZ0htNElocHliKzJOT2dGeDNhZ2sKOVFta1l4SmQxRkh4K2hKZFhLVDNQZE82T2g3TG9sOGtNOExsb2F4MEhaQk42T3d0ckZXZ2p5V21KOU1kblBENQpqalNFZnBPMWxFcmdybnJGa29nbThuSDVPdWcrR2E2UzBDNjluenpoVDR0cXplTUpYWFJTdFdMa3pCZ1p3Z3dHCi9ySFk2SEZYaHhwNUNRWWd2NGwraHlLc2dmTUZqbWtSMUNJNUpqcWhDY3VlaXRWdnBmcStPeFhUZUNQd3g1QU0KLzJIVzJQa0NnWUVBK0RGZksvTlorSFg2UzRqYkZKUDFlZ0wvckVvV3cwTmExSHp3QVl1a2FMejlOalhlQkVuaQo4VUF5eHMrTDYyWVJnSEZwcmhwRjV6YlJnZGowZ0ZaeTFxVTBZYm16aENEOUNSZm1SQmt1TlNKazdMQ1JZNHUxCmlQcGlRL0NwV1piR2NPZWZkZUgwb0ExTjVaU3RKNjY3QmxnM2dPSXVpRnRlSHZLeW01WTlkajhDZ1lFQTMrU2gKUkJMdnJhSmxCRTZqZmMwaDVxdnk5RDQxMnN3QWNpUWNydzRNMWk3M2d1Vk1GcWNQUlFabGZkSzF2Z0daVmRVNApMa3kvVWNGbUVNeEdoQkQ5RUsxZkxyc2Z6bXd6eE42L1R1amNBVmRPNkd0WDZRZi9EbFQ1UlVrRTJWajdWK3lZCkZLUWorc3R5dllaZHc5dU5FK3RRZW5hU3ZsZXpZcUNBZlh4R3dyY0NnWUEvWTB5dFN1KzFsMXdmb29waGpSQnEKNHcwdGtaYVN0RWNrY2V4U1dMbmF6am5WZUppRmUrRnNRRHMzcjVaS3ZyekZrekdzZDZWVzBoZGNGRzhOd0FhQQpiNTBiUUhScTBJb1Bvbno2ODN0cnNxY1lGRmh0bGliOUh3V3QyRzlJSkV2MlZoSFI1NjIwbXZGRUsxNjEvZGhpClhIR0FoMFBmSzRhMFhNUGxITkFCdlFLQmdRREZ3RzJENytuTWhqd05BdHc2dUIxeVhYdVlxUDN1US9NODNaS00KTjYrMDJnVDVrMGVTVm5vUk1HWWlMU01qTU14YldKbG5vNWYwUVFyQ1dYc0xHT284ZWJVeFZFdnlpZlZydElacQp6eGZMQTIrSnI0NFZJRi95SzdHRHRjdlhvVlZXd24xTTlmRmxpWjdOc1VsT1BiUXMzTkhYYUxXUjgycFkrWVNqCjBVbTZud0tCZ1FEMnN3Wkg4a01RS016Z3NQOTdzYmVNNVE5MWY1bUZxaEtuc3VCdGQyeTRQZVRud0dwWno1N3AKK3k3ZzBhbWFYWC9LS1NDRmdNbFZ2NGtsMU44aVlaRTN3M0xNUGJjaElpMCtkemFwS2V2RmoxdDNGV2Z3bm5YYwpQY2h4VlpkNzR1RHQrZFhlQ3c1V3BHbmlxc3Vzd2ZLMW5yRlFCZXJtVk1XRkdrUUUrUFpJZnc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: v1
kind: Service
metadata:
  name: argoproj-metrics-poc
  namespace: default
  labels:
    api: argoproj-metrics-poc
    apiserver: "true"
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    api: argoproj-metrics-poc
    apiserver: "true"
