---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metric-apiserver-controller
  namespace: default
  labels:
    api: metric-apiserver
    controller: "true"
spec:
  selector:
    matchLabels:
      api: metric-apiserver
      controller: "true"
  replicas: 1
  template:
    metadata:
      labels:
        api: metric-apiserver
        controller: "true"
    spec:
      containers:
      - name: controller
        image: metric
        command:
        - "./controller-manager"
        args:
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 100m
            memory: 300Mi
      volumes:
      - name: apiserver-certs
        secret:
          secretName: metric-apiserver
